import{a as w,S,i as c}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q="56452748-acb3c6ecf21893b07db51bc11",$="https://pixabay.com/api/";async function m(r,o){return(await w.get($,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:n,comments:L,downloads:v})=>`
    <li class="gallery-item">
      <a href="${i}">
        <img src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes</b><span>${t}</span></p>
        <p><b>Views</b><span>${n}</span></p>
        <p><b>Comments</b><span>${L}</span></p>
        <p><b>Downloads</b><span>${v}</span></p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){f.innerHTML=""}function b(){g.classList.add("loader--visible")}function l(){g.classList.remove("loader--visible")}function P(){h.classList.add("load-more--visible")}function d(){h.classList.remove("load-more--visible")}const O=document.querySelector(".form"),R=document.querySelector(".load-more");let u="",a=1,p=0;O.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(o){u=o,a=1,M(),d(),b();try{const s=await m(u,a);if(p=s.totalHits,l(),s.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(s.hits),s.hits.length<15||a*15>=p?d():P()}catch(s){l(),c.error({message:`Something went wrong: ${s.message}`,position:"topRight"})}}});R.addEventListener("click",async()=>{a+=1,b();try{const r=await m(u,a);l(),y(r.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),a*15>=p&&(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){l(),c.error({message:`Something went wrong: ${r.message}`,position:"topRight"})}});
//# sourceMappingURL=index.js.map
